In [ ]:
# TOTAL=TP+TN+FP+FN
# Model Accuracy
accuracy=(TP+TN)/TOTAL

In [ ]:
# ERROR RATE
ER=(FP+FN)/TOTAL
# OR
ER=1-accuracy

In [ ]:
# Sensitivity or recall score
SEN=(TP)/TP+FN

In [ ]:
# Specificity
SPE=(TN)/TN+FP

In [117]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix

In [5]:
df=pd.read_csv('diabetes.csv')
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [6]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [7]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [8]:
y=df["Outcome"]
x=df[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age']]

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=42)

In [10]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((614, 8), (154, 8), (614,), (154,))

In [11]:
614**0.5   #to find number of n_neighbors

24.779023386727733

In [12]:
nn=KNeighborsClassifier(n_neighbors=25)

In [13]:
model=nn.fit(x_train,y_train)

In [14]:
y_pred=model.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0])

In [15]:
cm=confusion_matrix(y_test,y_pred)
cm

array([[83, 16],
       [28, 27]])

In [16]:
TN=cm[0][0]
TN

np.int64(83)

In [17]:
FP=cm[0][1]
FP

np.int64(16)

In [18]:
FN=cm[1][0]
FN

np.int64(28)

In [19]:
TP=cm[1][1]
TP

np.int64(27)

In [20]:
accuracy=(TP+TN)/(TP+TN+FP+FN)
accuracy

np.float64(0.7142857142857143)

In [21]:
ER=1-accuracy
ER

np.float64(0.2857142857142857)

In [22]:
SEN=(TP)/TP+FN
SEN

np.float64(29.0)

In [26]:
SPE=(TN)/(TN+FP)
SPE

np.float64(0.8383838383838383)

In [24]:
# PRE=4
# GLOCOSE=95
# BP=55
# SKINTHIKNESS=30
# INSULIN=180
# BMI=29
# DPF=0.5
# AGE=51
Prediction=model.predict([[4,95,55,30,180,29,0.5,51]])
Prediction

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

array([0])

In [27]:
df=pd.read_csv('data_breast_cancer.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [28]:
df.isna().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: int64

In [32]:
df=df.drop(columns=["id","Unnamed: 32"])
df.sample()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
91,M,15.37,22.76,100.2,728.2,0.092,0.1036,0.1122,0.07483,0.1717,...,16.43,25.84,107.5,830.9,0.1257,0.1997,0.2846,0.1476,0.2556,0.06828

In [33]:
df.columns

Index(['diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [41]:
y=df["diagnosis"]
x=df[['radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst']]

In [42]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=42)

In [43]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((455, 30), (114, 30), (455,), (114,))

In [44]:
455**0.5

21.330729007701542

In [45]:
nn=KNeighborsClassifier(n_neighbors=21)

In [46]:
model=nn.fit(x_train,y_train)

In [47]:
y_pred=model.predict(x_test)
y_pred

array(['B', 'M', 'M', 'B', 'B', 'M', 'M', 'M', 'B', 'B', 'B', 'M', 'B',
       'M', 'B', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'B', 'B', 'B',
       'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'M',
       'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M',
       'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'B',
       'B', 'M', 'M', 'B', 'B', 'M', 'M', 'B', 'M', 'B', 'B', 'B', 'B',
       'B', 'B', 'M', 'B', 'B', 'M', 'M', 'M', 'B', 'M', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'M', 'B', 'M', 'M',
       'B', 'B', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'M'], dtype=object)

In [48]:
cm=confusion_matrix(y_test,y_pred)
cm

array([[71,  0],
       [ 4, 39]])

In [58]:
TN=cm[0][0]
FP=cm[0][1]
FN=cm[1][0]
TP=cm[1][1]

In [63]:
accuracy=(TP+TN)/(TP+TN+FP+FN)
accuracy

np.float64(0.9649122807017544)

In [64]:
ER=1-accuracy
ER

np.float64(0.03508771929824561)

In [65]:
SEN=(TP)/TP+FN
SEN

np.float64(5.0)

In [66]:
SPE=(TN)/(TN+FP)
SPE

np.float64(1.0)

In [72]:
df=pd.read_csv('PlayTennis.csv')
df.head()

    outlook  temp humidity  windy play
0     sunny   hot     high  False   no
1     sunny   hot     high   True   no
2  overcast   hot     high  False  yes
3     rainy  mild     high  False  yes
4     rainy  cool   normal  False  yes

In [73]:
df=pd.get_dummies(data=df,drop_first=True)
df

,windy,outlook_rainy,outlook_sunny,temp_hot,temp_mild,humidity_normal,play_yes
0,False,False,True,True,False,False,False
1,True,False,True,True,False,False,False
2,False,False,False,True,False,False,True
3,False,True,False,False,True,False,True
4,False,True,False,False,False,True,True
5,True,True,False,False,False,True,False
6,True,False,False,False,False,True,True
7,False,False,True,False,True,False,False
8,False,False,True,False,False,True,True
9,False,True,False,False,True,True,True
10,True,False,True,False,True,True,True
11,True,False,False,False,True,False,True
12,False,False,False,True,False,True,True
13,True,True,False,False,True,False,False

In [74]:
df.columns

Index(['windy', 'outlook_rainy', 'outlook_sunny', 'temp_hot', 'temp_mild',
       'humidity_normal', 'play_yes'],
      dtype='object')

In [75]:
y=df["play_yes"]
x=df[['windy', 'outlook_rainy', 'outlook_sunny', 'temp_hot', 'temp_mild',
       'humidity_normal']]

In [76]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=42)

In [77]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((11, 6), (3, 6), (11,), (3,))

In [78]:
11**0.5

3.3166247903554

In [83]:
nn=KNeighborsClassifier(n_neighbors=3)

In [84]:
model=nn.fit(x_train,y_train)

In [85]:
y_pred=model.predict(x_test)
y_pred

array([ True, False,  True])

In [86]:
cm=confusion_matrix(y_test,y_pred)
cm

array([[0, 1],
       [1, 1]])

In [87]:
TN=cm[0][0]
FP=cm[0][1]
FN=cm[1][0]
TP=cm[1][1]

In [88]:
accuracy=(TP+TN)/(TP+TN+FP+FN)
accuracy

np.float64(0.3333333333333333)

In [89]:
SEN=(TP)/TP+FN
SEN

np.float64(2.0)

In [90]:
ER=1-accuracy
ER

np.float64(0.6666666666666667)

In [91]:
SPE=(TN)/(TN+FP)
SPE

np.float64(0.0)

In [92]:
df.head()

,windy,outlook_rainy,outlook_sunny,temp_hot,temp_mild,humidity_normal,play_yes
0,False,False,True,True,False,False,False
1,True,False,True,True,False,False,False
2,False,False,False,True,False,False,True
3,False,True,False,False,True,False,True
4,False,True,False,False,False,True,True

In [95]:
# atm=rainy,tem=cool,humidity=high,windy=true,
Prediction=model.predict([[1,1,0,0,0,0]])
Prediction

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

array([False])

In [96]:
df=pd.read_csv('Fish.csv')
df.head()

  Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [97]:
df.columns

Index(['Species', 'Weight', 'Length1', 'Length2', 'Length3', 'Height',
       'Width'],
      dtype='object')

In [98]:
y=df["Species"]
x=df[['Weight', 'Length1', 'Length2', 'Length3', 'Height',
       'Width']]

In [99]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=42)

In [100]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((127, 6), (32, 6), (127,), (32,))

In [101]:
127**0.5

11.269427669584644

In [104]:
nn=KNeighborsClassifier(n_neighbors=11)

In [105]:
model=nn.fit(x_train,y_train)

In [106]:
y_pred=model.predict(x_test)
y_pred

array(['Perch', 'Smelt', 'Roach', 'Perch', 'Roach', 'Perch', 'Smelt',
       'Roach', 'Roach', 'Perch', 'Bream', 'Perch', 'Bream', 'Roach',
       'Bream', 'Perch', 'Perch', 'Perch', 'Perch', 'Bream', 'Smelt',
       'Bream', 'Bream', 'Bream', 'Perch', 'Perch', 'Roach', 'Perch',
       'Smelt', 'Smelt', 'Bream', 'Perch'], dtype=object)

In [107]:
cm=confusion_matrix(y_test,y_pred)
cm

array([[7, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 6, 0, 3, 0, 0],
       [1, 0, 1, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 5, 0],
       [0, 0, 3, 0, 0, 0, 0]])

In [109]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [110]:
# weight=85,length=25.0,length2=20.0,length33=31,height=6.0 with2.5
Prediction=model.predict([[85,25,20,31,6,2.5]])
Prediction

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

array(['Perch'], dtype=object)

In [120]:
df=pd.read_csv('Iris.csv')
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [121]:
df=df.drop(columns="Id")

In [122]:
df.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [123]:
df.columns

Index(['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [124]:
y=df["Species"]
x=df[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',]]

In [125]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=42)

In [126]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((80, 4), (20, 4), (80,), (20,))

In [127]:
80**0.5

8.94427190999916

In [128]:
nn=KNeighborsClassifier(n_neighbors=11)

In [129]:
model=nn.fit(x_train,y_train)

In [130]:
y_pred=model.predict(x_test)
y_pred

array(['Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa'], dtype=object)

In [131]:
cm=confusion_matrix(y_test,y_pred)
cm

array([[12,  0],
       [ 0,  8]])

In [132]:
TN=cm[0][0]
FP=cm[0][1]
FN=cm[1][0]
TP=cm[1][1]

In [133]:
df.columns

Index(['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')